-- MySQL Script generated by MySQL Workbench
-- Fri Jan 16 09:14:16 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schéma cyberhoot - en cas de réinitialisation, 
-- ce schéma permet de récupérer la base de donnée
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schéma cyberhoot
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cyberhoot` DEFAULT CHARACTER SET utf8 ;
USE `cyberhoot` ;

-- -----------------------------------------------------
-- Table `cyberhoot`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cyberhoot`.`USER` (
  `idUSER` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `hashpassword` VARCHAR(512) NULL,
  `emailUser` VARCHAR(45) NULL,
  PRIMARY KEY (`idUSER`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `cyberhoot`.`QUIZ`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cyberhoot`.`QUIZ` (
  `idQUIZ` INT NOT NULL AUTO_INCREMENT,
  `idCreatedByUser` INT NOT NULL,
  `difficulty` ENUM('HARD', 'MEDIUM', 'EASY') NULL,
  `title` VARCHAR(45) NULL,
  `statut` ENUM('MODIFIED', 'PUBLISHED', 'DRAFT', 'PENDING') NULL,
  `category` ENUM('PHISHING', 'MALWARE', 'RESEAUX', 'MOTS_DE_PASSE', 'INGENIERIE_SOCIALE', 'AUTRE', 'CATEGORIE_TEST') NULL,
  `createdAt` DATE NULL,
  PRIMARY KEY (`idQUIZ`),
  INDEX `idCreatedByUser_idx` (`idCreatedByUser` ASC) VISIBLE,
  CONSTRAINT `fk_quiz_creator`
    FOREIGN KEY (`idCreatedByUser`)
    REFERENCES `cyberhoot`.`USER` (`idUSER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cyberhoot`.`BADGES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cyberhoot`.`BADGES` (
  `idBADGES` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `image` BLOB NULL,
  `idQuiz` INT NOT NULL,
  PRIMARY KEY (`idBADGES`),
  INDEX `idQuiz_idx` (`idQuiz` ASC) VISIBLE,
  CONSTRAINT `fk_badges_quiz`
    FOREIGN KEY (`idQuiz`)
    REFERENCES `cyberhoot`.`QUIZ` (`idQUIZ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cyberhoot`.`NOTIFICATIONS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cyberhoot`.`NOTIFICATIONS` (
  `idNOTIFICATIONS` INT NOT NULL AUTO_INCREMENT,
  `idUser` INT NOT NULL,
  `type` ENUM('new_quiz', 'badge_earned', 'reminder') NULL,
  `message` VARCHAR(45) NULL,
  `sentAt` DATE NULL,
  `emailNotif` VARCHAR(45) NULL,
  PRIMARY KEY (`idNOTIFICATIONS`),
  INDEX `idUser_idx` (`idUser` ASC) VISIBLE,
  CONSTRAINT `fk_notification_user`
    FOREIGN KEY (`idUser`)
    REFERENCES `cyberhoot`.`USER` (`idUSER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cyberhoot`.`user_badges`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cyberhoot`.`user_badges` (
  `idUser` INT NOT NULL,
  `idBadge` INT NOT NULL,
  `obtainedAt` DATE NULL,
  PRIMARY KEY (`idUser`, `idBadge`),
  INDEX `idBadge_idx` (`idBadge` ASC) VISIBLE,
  CONSTRAINT `fk_user_badges_user`
    FOREIGN KEY (`idUser`)
    REFERENCES `cyberhoot`.`USER` (`idUSER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_badges_badge`
    FOREIGN KEY (`idBadge`)
    REFERENCES `cyberhoot`.`BADGES` (`idBADGES`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cyberhoot`.`QUESTION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cyberhoot`.`QUESTION` (
  `idQUESTION` INT NOT NULL AUTO_INCREMENT,
  `idQuestionFromQuiz` INT NOT NULL,
  `QuestionText` VARCHAR(500) NULL,
  PRIMARY KEY (`idQUESTION`),
  INDEX `idQuestionFromQuiz_idx` (`idQuestionFromQuiz` ASC) VISIBLE,
  CONSTRAINT `fk_question_quiz`
    FOREIGN KEY (`idQuestionFromQuiz`)
    REFERENCES `cyberhoot`.`QUIZ` (`idQUIZ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cyberhoot`.`RESPONSE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cyberhoot`.`RESPONSE` (
  `idRESPONSE` INT NOT NULL AUTO_INCREMENT,
  `idResponseFromQuestion` INT NOT NULL,
  `responseText` VARCHAR(500) NULL,
  `isCorrect` TINYINT(1) NULL,
  PRIMARY KEY (`idRESPONSE`),
  INDEX `idResponseFromQuestion_idx` (`idResponseFromQuestion` ASC) VISIBLE,
  CONSTRAINT `fk_response_question`
    FOREIGN KEY (`idResponseFromQuestion`)
    REFERENCES `cyberhoot`.`QUESTION` (`idQUESTION`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cyberhoot`.`MEDIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cyberhoot`.`MEDIA` (
  `idMEDIA` INT NOT NULL AUTO_INCREMENT,
  `idMediaFromQuestion` INT NULL,
  `idMediaFromResponse` INT NULL,
  `mediaUrl` VARCHAR(255) NULL,
  `mediaType` VARCHAR(50) NULL,
  `mediaLabel` VARCHAR(255) NULL,
  PRIMARY KEY (`idMEDIA`),
  INDEX `idMediaFromQuestion_idx` (`idMediaFromQuestion` ASC) VISIBLE,
  INDEX `idMediaFromResponse_idx` (`idMediaFromResponse` ASC) VISIBLE,
  CONSTRAINT `fk_media_question`
    FOREIGN KEY (`idMediaFromQuestion`)
    REFERENCES `cyberhoot`.`QUESTION` (`idQUESTION`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_media_response`
    FOREIGN KEY (`idMediaFromResponse`)
    REFERENCES `cyberhoot`.`RESPONSE` (`idRESPONSE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cyberhoot`.`RESULT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cyberhoot`.`RESULT` (
  `idRESULT` INT NOT NULL AUTO_INCREMENT,
  `idQUIZinResult` INT NOT NULL,
  `idUSERinResult` INT NOT NULL,
  `date` DATE NULL,
  `answer` TEXT NULL,
  `score` INT NULL,
  `totalQuestions` INT NULL,
  PRIMARY KEY (`idRESULT`),
  INDEX `idQUIZ_idx` (`idQUIZinResult` ASC) VISIBLE,
  INDEX `idUSERinResult_idx` (`idUSERinResult` ASC) VISIBLE,
  CONSTRAINT `fk_result_quiz`
    FOREIGN KEY (`idQUIZinResult`)
    REFERENCES `cyberhoot`.`QUIZ` (`idQUIZ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_result_user`
    FOREIGN KEY (`idUSERinResult`)
    REFERENCES `cyberhoot`.`USER` (`idUSER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cyberhoot`.`CONNECTION_LOG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cyberhoot`.`CONNECTION_LOG` (
  `idConnection_log` INT NOT NULL AUTO_INCREMENT,
  `idUserForConnection` INT NOT NULL,
  PRIMARY KEY (`idConnection_log`),
  INDEX `idUserForConnection_idx` (`idUserForConnection` ASC) VISIBLE,
  CONSTRAINT `fk_connectionlog_user`
    FOREIGN KEY (`idUserForConnection`)
    REFERENCES `cyberhoot`.`USER` (`idUSER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cyberhoot`.`ROLES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cyberhoot`.`ROLES` (
  `idROLES` INT NOT NULL AUTO_INCREMENT,
  `nameRoles` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `nameRoles_UNIQUE` (`nameRoles` ASC) VISIBLE,
  PRIMARY KEY (`idROLES`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cyberhoot`.`userToRoles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cyberhoot`.`userToRoles` (
  `idROLES` INT NOT NULL,
  `idUser` INT NOT NULL,
  `userToRole_id` INT NOT NULL AUTO_INCREMENT,
  INDEX `idRoles_idx` (`idROLES` ASC) VISIBLE,
  INDEX `idUser_idx` (`idUser` ASC) VISIBLE,
  PRIMARY KEY (`userToRole_id`),
  CONSTRAINT `fk_usertoroles_user`
    FOREIGN KEY (`idUser`)
    REFERENCES `cyberhoot`.`USER` (`idUSER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usertoroles_roles`
    FOREIGN KEY (`idROLES`)
    REFERENCES `cyberhoot`.`ROLES` (`idROLES`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
